backend:
  name: github
  repo: amykapernick/blog-posts

media_folder: img
public_folder: img/blog

collections:
  - name: blog
    label: Blog
    folder: posts
    create: true
    editor:
      preview: false
    fields:
      - {
          name: templateKey,
          label: Template Key,
          widget: hidden,
          default: blog-post,
        }
      - {
          name: draft,
          label: Draft,
          widget: boolean,
          default: false,
          required: false,
        }
      - { name: title, label: Title }
      - {
          name: publishDate,
          label: "Publish Date",
          widget: date,
          format: "YYYY-MM-DD",
        }
      - {
          name: updateDate,
          label: "Update Date",
          widget: date,
          format: "YYYY-MM-DD",
        }
      - { name: description, label: "Meta Description", widget: text }
      - {
          name: mainBlog,
          label: "Main Blog",
          widget: select,
          default: "Amy Goes To Perth",
          options: ["Amy Goes To Perth", "AimHigher", "The Freelance Guide"],
        }
      - { name: tags, label: Tags, widget: list }
      - { name: featuredImage, label: Featured Image, widget: image }
      - { name: body, label: Body, widget: markdown }
