backend:
  name: github
  repo: amykapernick/blog-posts

media_folder: img
public_folder: img/blog

collections:
  - name: blog
    label: Blog
    folder: posts
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - { name: publishDate, label: "Publish Date", widget: date, format: "YYYY-MM-DD" }
      - { name: updateDate, label: "Update Date", widget: date, format: "YYYY-MM-DD" }
      - { name: description, label: "Meta Description", widget: text }
      - { name: tags, label: Tags, widget: list }
      - { name: featuredImage, label: Featured Image, widget: image }
      - { name: body, label: Body, widget: markdown}