backend:
  name: github
  repo: amykapernick/amygoestoperth
  branch: netlify-gatsby

media_folder: img
public_folder: img

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - { name: publishDate, label: "Publish Date", widget: date, format: "DD/MM/YYYY" }
      - { name: updateDate, label: "Update Date", widget: date, format: "DD/MM/YYYY" }
      - { name: description, label: "Meta Description", widget: text }
      - { name: tags, label: Tags, widget: list }
      - { name: featuredImage, label: Featured Image, widget: image }
      - { name: body, label: Body, widget: markdown}